### ISSUE TITLE
Requires code for other tasks. 

### ISSUE THREAD

**Issue by WinterShiver** [tangminji/STGN-sst#4]
Would the code for other tasks (esp. NoisyNER and wikiHow) be released?

**Comment by tangminji** [comment]
Ok, we will release the code soon.

**Comment by tangminji** [comment]
Other experiments was adpated from their original code and data, and you should follow their own instructions.

-  NoisyNER: 
   - [our code](https://github.com/tangminji/STGN-NoisyNER)
   - [original work](https://github.com/uds-lsv/noise-estimation)

- wikiHow: 
  - [our code](https://github.com/tangminji/STGN-wikiHow) 
  - [original work](https://github.com/zharry29/wikihow-goal-step)
